IF OBJECT_ID('[dbo].[GetRef]') IS NOT NULL
	DROP PROCEDURE [dbo].[GetRef];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[GetRef] AS
BEGIN
SELECT  Reference FROM dbo.WidgetReferences
END

GO
