IF OBJECT_ID('[dbo].[GetSuppliers]') IS NOT NULL
	DROP PROCEDURE [dbo].[GetSuppliers];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[GetSuppliers] AS
BEGIN
SELECT * FROM dbo.DM_SUPPLIERS
END

GO
